# Generated by Django 2.2.3 on 2019-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='Cook_time',
            field=models.CharField(default=1, max_length=40),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Heading_first',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Heading_second',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Heading_third',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Ingredients_content_five',
            field=models.TextField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Ingredients_content_four',
            field=models.TextField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Ingredients_content_one',
            field=models.TextField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Ingredients_content_three',
            field=models.TextField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Ingredients_content_two',
            field=models.TextField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Key_Ingredients',
            field=models.TextField(default=1, max_length=300),
        ),
        migrations.AddField(
            model_name='recipes',
            name='Prep_time',
            field=models.CharField(default=1, max_length=40),
        ),
        migrations.AddField(
            model_name='recipes',
            name='content_first',
            field=models.TextField(default=1, max_length=300),
        ),
        migrations.AddField(
            model_name='recipes',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='content_second',
            field=models.TextField(default=1, max_length=300),
        ),
        migrations.AddField(
            model_name='recipes',
            name='content_third',
            field=models.TextField(default=1, max_length=300),
        ),
    ]
