# Generated by Django 2.2.3 on 2019-07-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_auto_20190722_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='Heading_first',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Heading_second',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Heading_third',
            field=models.CharField(blank=True, default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients_content_five',
            field=models.TextField(blank=True, default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients_content_four',
            field=models.TextField(blank=True, default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients_content_one',
            field=models.TextField(blank=True, default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients_content_three',
            field=models.TextField(blank=True, default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Ingredients_content_two',
            field=models.TextField(blank=True, default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='Key_Ingredients',
            field=models.TextField(blank=True, default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='content_first',
            field=models.TextField(blank=True, default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='content_second',
            field=models.TextField(blank=True, default=1, max_length=300),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='content_third',
            field=models.TextField(blank=True, default=1, max_length=300),
        ),
    ]
